### ISSUE TITLE
`iocage get property` should default to getting properties of all jails

### ISSUE THREAD

**Issue by moviuro** [freqlabs/iocage#6]
e.g. `iocage get resolver` should return resolvers of all jails, same as `iocage get ip6_addr` would return all IPv6 addresses of all jails.
Output should be machine-parseable or human readable (same switches as `iocage list` maybe?)
This functionality should also work with `iocage get property ALL`

**Comment by freqlabs** [comment]
This feature has been added in commit ddc4f77d598e5b072b64530f2d5fcfddda43c3b7
